[WIP] Forums
codalab/competitions-v2 pull request #570
Opened 2020-11-20 00:57 UTC by ckcollab

# A brief description of the purpose of the changes contained in this PR.
Forums..!

# Issues this PR resolves
Relates to #352 

# A checklist for hand testing
- [ ] Can make a thread
- [ ] Get notified as admin about new threads
- [ ] Get notified of new posts in a thread you create
- [ ] Get notified about posts in a thread you're participating in
- [ ] Can CRUD posts

# Checklist
- [ ] Code review by me 
- [ ] Hand tested by me 
- [ ] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] Ready to merge

2020-11-20 00:58 UTC, ckcollab commented
Current progress: old style base in, used bootstrap for templates so that frontend will need to be completed

2020-11-23 21:35 UTC, Logan-Ruf requested changes

2020-11-23 21:35 UTC, Logan-Ruf commented on src/apps/profiles/migrations/0006_user_allow_forum_notifications.py
> +    ]
This can be merged into the previous migration.

2020-11-23 21:35 UTC, Logan-Ruf commented on src/apps/forums/views.py
> +def pin_thread(request, thread_pk):
Should this be an `@action`?

2020-12-05 02:43 UTC, merged