[WIP] task panel UI improvements
codalab/competitions-v2 pull request #620
Opened 2021-01-04 22:50 UTC by dde6khkg

# Template
This is a template. While not all sections are necessary, depending on the size and complexity of the PR,
more information is better. 

# @ mention of reviewers
...

# A brief description of the purpose of the changes contained in this PR.
...

# Issues this PR resolves
...

# Known issues to be addressed in a separate PR
...

# A checklist for hand testing
- [ ] add checklist here

# Any relevant files for testing
[link]('#') to any relevant files (or drag and drop into github)

# Misc. comments
...

# Checklist
- [ ] Code review by me 
- [ ] Hand tested by me 
- [ ] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] Ready to merge

2021-01-08 02:03 UTC, Logan-Ruf requested changes

2021-01-08 02:03 UTC, Logan-Ruf commented on src/static/riot/tasks/management.tag
> +            <td>{ task.shared_with.join(', ') }</td>
When you change from using method fields to nested serializer you will have to change this to something like.
```suggestion
            <td class="benchmark-row">{ task.competitions.title }, { task.competitions.id }</td>
            <td>{ task.shared_with.name }</td>
```
You could even add a link to the user's profile if you think it fits.

2021-01-08 02:05 UTC, ckcollab commented on src/apps/api/views/tasks.py
>              qs = qs.annotate(validated=Subquery(task_validate_qs.values('pk')[:1]))
we made this way faster actually just a few moments ago, that is correct though. 

I believe the rationale was to keep things simple, making this data "live" is relatively easy vs making it into a property we have to sync whenever submissions are deleted/such. we want a valid submission that exists

2021-01-08 17:11 UTC, dde6khkg commented on src/apps/api/serializers/tasks.py
> +    shared_with = serializers.SerializerMethodField()
The method fields are used to reduce queries. I'm getting everything I need in the viewset in 1 or two queries and passing what I need as context. I think doing it that way will cause queries to scale with tasks right?

2021-01-08 19:09 UTC, Logan-Ruf requested changes
Share modal doesn't clear after you share then open another task.
![image](https://user-images.githubusercontent.com/16579931/104054446-f3650300-51a1-11eb-8f19-bc760bbf04ea.png)

2021-01-14 18:18 UTC, Logan-Ruf commented
Tested sharing tasks and making sure those tasks are shown to the user that it was shared too.

2021-01-14 18:19 UTC, merged